default_settings: null
behaviors:
  CarAgent:
    trainer_type: poca
    hyperparameters:
      batch_size: 1024
      buffer_size: 4096
      learning_rate: 0.0001
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
      curiosity:
        gamma: 0.99
        strength: 0.02
        network_settings:
          normalize: false
          hidden_units: 256
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
        learning_rate: 0.0003
        encoding_size: null
      gail:
        gamma: 0.99
        strength: 0.01
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
        learning_rate: 0.0003
        encoding_size: null
        use_actions: false
        use_vail: false
        demo_path: C:\Users\steffanutto\Desktop\KARlab_UC3_Unity\POC1\Assets\Demonstrations\BCScenario2FT.demo
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 200000000
    time_horizon: 32
    summary_freq: 50000
    threaded: false
    self_play: null
